[build]
  publish = "."
  command = "echo 'Deploy do frontend Fala Alunos'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
  conditions = {Role = ["!admin"]}

# Configurações para SPA
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

# Redirecionar para HTTPS
[[redirects]]
  from = "http://fala-alunos.netlify.app/*"
  to = "https://fala-alunos.netlify.app/:splat"
  status = 301
  force = true 